name: ğŸš¦ ESLint and Test

on:
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v2

      - name: ğŸ“¦ Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Change this to the appropriate Node.js version

      - name: ğŸ“¥ Install ESLint
        run: npm install eslint --global

      - name: ğŸ“¥ Install dependencies
        run: npm install

      - name: ğŸš¨ Run ESLint
        run: npm run-script eslint

      - name: â–¶ï¸ Run tests
        run: npm test
