name: Release

on:
  push:
    branches: [ beta ]

jobs:
  quality:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ 15.x]
        os: [ubuntu-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/beta' }}
    needs: [quality]
    steps:

      - name: Set up authentication token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v9.0.16
        env:
          PACKAGEJSON_DIR: 'projects/ngx-ftx-forms'
        with:
          commit-message: 'ðŸ¤–: bumps version to {{version}} [skip ci] [CI]'
          version-type: 'patch'
      - run: npm run-script build
      - run: cd dist/ngx-ftx-forms && npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
